question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The World Cup is held every 6 years.", "answer": "False"},
    {"text": "Pele is the only player to have won three World Cups.", "answer": "True"},
    {"text": "The first World Cup was held in 1930.", "answer": "True"},
    {"text": "Real Madrid has won the most UEFA Champions League titles.", "answer": "True"},
    {"text": "The offside rule was introduced in 1925.", "answer": "False"},
    {"text": "A standard football match is 120 minutes long.", "answer": "False"},
    {"text": "In the Premier League, the team with the most points at the end of the season wins the title.", "answer": "True"},
    {"text": "Lionel Messi has won more Ballon d'Or awards than Cristiano Ronaldo.", "answer": "True"},
    {"text": "Tomatoes are vegetables.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "Sushi always contains raw fish.", "answer": "False"},
    {"text": "French fries originated from France.", "answer": "False"},
    {"text": "The main ingredient in guacamole is avocado.", "answer": "True"},
    {"text": "Watermelon is both a fruit and a vegetable.", "answer": "True"},
    {"text": "Caviar is made from fish eggs.", "answer": "True"},
    {"text": "Brie is a type of cheese.", "answer": "True"},
    {"text": "Champagne can only be produced in the Champagne region of France.", "answer": "True"},
    {"text": "Ketchup was once sold as medicine.", "answer": "True"},
    {"text": "Coffee is made from berries.", "answer": "True"},
    {"text": "Bananas grow on trees.", "answer": "False"},
]
